services:
  lavalink:
    image: ghcr.io/lavalink-devs/lavalink:dev
    restart: always
    ports:
      - "2333:2333"
    volumes:
      - ./application.yml:/opt/Lavalink/application.yml

  bot:
    build: .
    restart: always
    env_file:
      - .env
    depends_on:
      - lavalink